#!/bin/bash

# crontab -e
# 0 0 * * * /bin/sh /home/ssabbah/Desktop/init/script/04

# Create a file with the md5sum of the crontab, before you start using the script
# md5sum /etc/crontab | cut -d " " -f1 > /root/result


var=$(cat result)

var2=$(md5sum /etc/crontab | cut -d " " -f1)

if [$var != $var2]; then
	echo "Crontab was changed" | mail -s "Notification from script" root@localhost.localdomain
	echo $var2 > result
fi
